In [1]:
import numpy as np
import pandas as pd

In [2]:

# creating a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.size)   # total number of elements in the array
print(arr.shape)  # shape of array (rows, columns)
print(arr.ndim)   # number of dimensions of the array


6
(2, 3)
2


In [4]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])  # np.array() makes a NumPy array from a list
print("Original array:", arr)
print("Original shape:", arr.shape)   # .shape tells number of rows and columns

# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)     # .reshape() changes shape without changing data
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)
[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


In [7]:

def pythonsum(n):
    a = range(n)            # create a list of numbers 0 to n-1 for squares
    b = range(n)            # create a list of numbers 0 to n-1 for cubes
    c = []                  # create an empty list to store the results
    
    for i in range(n):      
        a[i] = i ** 2       # square of i
        b[i] = i ** 3       # cube of i
        c.append(a[i] + b[i])  # add square and cube and store in c
        
    return c                # return the final list

In [8]:
def pythonsum(n):
    a = [0] * n       # make a list of n zeros for squares
    b = [0] * n       # make a list of n zeros for cubes
    c = []            # make an empty list to store sum of square + cube
    for i in range(n):
        a[i] = i ** 2     # store square of i in list a
        b[i] = i ** 3     # store cube of i in list b
        c.append(a[i] + b[i])  # add square + cube and save in list c
    return c           # give back the final list c

In [9]:
import numpy as np

def numpysum(n):
    a = np.arange(n) ** 2  # make numbers from 0 to n-1 and square each number
    b = np.arange(n) ** 3  # make numbers from 0 to n-1 and cube each number
    c = a + b              # add the squared and cubed numbers one by one (no loops!)
    return c               # give back the result array

In [10]:
numpysum(4)

array([ 0,  2, 12, 36])

# Creating Arrays from Sequences
# a list of numbers will create a 1D array,
# a list of lists will create a 2D array,
# further nested lists will create higher-dimensional arrays. 
# In general, any array object is called an ndarray in NumPy.

In [11]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [12]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

| Name       | Alias(es)       | Size   | Range                           |
| ---------- | --------------- | ------ | ------------------------------- |
| `np.int8`  | `int8`          | 8-bit  | −128 to 127                     |
| `np.int16` | `int16`         | 16-bit | −32,768 to 32,767               |
| `np.int32` | `int32`, `int_` | 32-bit | −2,147,483,648 to 2,147,483,647 |
| `np.int64` | `int64`         | 64-bit | −9.2e18 to 9.2e18 (approx.)     |


In [16]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# You will get an error, why?

#You are trying to put numbers too big for int8 (like 128 or 129) into a NumPy array.

#In the future, NumPy will not allow this automatic conversion, so it may give an error instead of overflowing.

/var/folders/kv/8mr5m76n0dqdlq4dgh4ld6xc0000gn/T/ipykernel_3231/665357515.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
/var/folders/kv/8mr5m76n0dqdlq4dgh4ld6xc0000gn/T/ipykernel_3231/665357515.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [21]:
#ARRAY CREATION FUNCTIONS
import numpy as np
np.arange(10) #0 TO BEFORE 10, Step Value 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2, 10, dtype=float) # create numbers from 2 to 9 (10 not included), default step=1, as floats

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
np.arange(2, 3, 0.1) # create numbers from 2 to just before 3, step=0.1

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

# best practice for numpy.arange is to use integer start, end, and step values.

In [19]:
np.linspace(1., 4., 6)# np.linspace(start, stop, num) → makes 'num' evenly spaced numbers from start to stop

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [24]:
#2D Array Creation
#The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define 
#properties of special matrices represented as 2D arrays.
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.eye(3, 5, k=-2) #optional k argument, what happens when k>0, k<0

# k = 0 → main diagonal (default)

# k > 0 → diagonal above the main diagonal

# k < 0 → diagonal below the main diagonal

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# returns a 1D array that is only the diagonal elements. 
# The two array creation functions can be helpful while doing linear algebra, as such:

In [34]:
import numpy as np
np.diag([1, 2, 3])  # create a diagonal matrix with 1, 2, 3 on the main diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [32]:
np.diag([1, 2, 3], 1) # create a diagonal matrix with 1, 2, 3 on the diagonal **above** the main diagonal

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [33]:
a = np.array([[1, 2], [3, 4]]) # create a 2x2 array
np.diag(a)

array([1, 4])

# np.diag(v, k=1):

# When v is a 1D array, np.diag creates a 2D square matrix with v placed along the k-th diagonal.

# k=1 → the diagonal above the main (first superdiagonal).

# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.

# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4

# # Diagonal values are placed at positions: (0,1), (1,2), (2,3)

In [35]:
# create a 3x2 array filled with 0s
arr = np.zeros((3,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [36]:
# create a 2x3 array filled with 1s
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
# create a 2x3 array with random numbers between 0 and 1
arr = np.random.rand(2,3)
print(arr)

[[0.28986574 0.70895214 0.85509381]
 [0.13950279 0.98153464 0.53872187]]


In [38]:
# create row and column indices for a 2x3 grid
idx = np.indices((2,3))
print(idx)

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


# Vandermonde Matrix

In [40]:
# Vandermonde Matrix

np.vander(np.linspace(0, 2, 5), 2) # create a Vandermonde matrix from 5 numbers evenly spaced between 0 and 2, 2 columns

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [41]:
np.vander([1, 2, 3, 4], 2) # create a Vandermonde matrix from a list of 4 numbers, 2 columns

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [42]:
np.vander((1, 2, 3, 4), 4) # create a Vandermonde matrix from a tuple of 4 numbers, 4 columns

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

| x | x¹ | x⁰ |
| - | -- | -- |
| 1 | 1  | 1  |
| 2 | 2  | 1  |
| 3 | 3  | 1  |
| 4 | 4  | 1  |


| x | x³ | x² | x¹ | x⁰ |
| - | -- | -- | -- | -- |
| 1 | 1  | 1  | 1  | 1  |
| 2 | 8  | 4  | 2  | 1  |
| 3 | 27 | 9  | 3  | 1  |
| 4 | 64 | 16 | 4  | 1  |


# np.vander(x, N) creates a Vandermonde matrix from a 1D input array x.

# [[x₁**(N-1), x₁**(N-2), ..., x₁**0],
#  [x₂**(N-1), x₂**(N-2), ..., x₂**0],
#  ...
#  [xₙ**(N-1), xₙ**(N-2), ..., xₙ**0]]

# So each row is a decreasing power of an element from x.


In [49]:
np.vander(np.linspace(0, 2, 5), 2)
# N = 2 → two columns: x**1, x**0

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [50]:
np.linspace(0, 2, 5) # → [0. , 0.5, 1. , 1.5, 2. ]

array([0. , 0.5, 1. , 1.5, 2. ])

In [51]:
np.vander([1, 2, 3, 4], 2)
#Input: [1, 2, 3, 4]
# No of Columns 2
#N = 4 → columns: x**3, x**2, x**1, x**0

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

# Each row is [x**3, x**2, x, 1] for each x in the input.

| Code                                 | Shape    | Meaning                                           |
| ------------------------------------ | -------- | ------------------------------------------------- |
| `np.vander(np.linspace(0, 2, 5), 2)` | `(5, 2)` | 2-column Vandermonde matrix of `[0, 0.5, ..., 2]` |
| `np.vander([1, 2, 3, 4], 2)`         | `(4, 2)` | Powers: `[x, 1]` for each x                       |
| `np.vander((1, 2, 3, 4), 4)`         | `(4, 4)` | Powers: `[x**3, x**2, x, 1]`                      |
